==463071== Memcheck, a memory error detector
==463071== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==463071== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==463071== Command: ./get_next_line.out 5 r
==463071== Parent PID: 463070
==463071== 
==463071== Invalid read of size 1
==463071==    at 0x10A3E8: ft_strlen (in /home/diego/Documents/Git/mylibs/myunittest/get_next_line.out)
==463071==    by 0x10A330: handle_string_specifier (in /home/diego/Documents/Git/mylibs/myunittest/get_next_line.out)
==463071==    by 0x10A10C: handle_format_specifier (in /home/diego/Documents/Git/mylibs/myunittest/get_next_line.out)
==463071==    by 0x10A050: process_format (in /home/diego/Documents/Git/mylibs/myunittest/get_next_line.out)
==463071==    by 0x109FA2: ft_snprintf (in /home/diego/Documents/Git/mylibs/myunittest/get_next_line.out)
==463071==    by 0x109544: tests (src/myunit.c:82)
==463071==    by 0x10996E: main (src/myunit.c:173)
==463071==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==463071== 
==463071== 
==463071== Process terminating with default action of signal 11 (SIGSEGV)
==463071==  Access not within mapped region at address 0x0
==463071==    at 0x10A3E8: ft_strlen (in /home/diego/Documents/Git/mylibs/myunittest/get_next_line.out)
==463071==    by 0x10A330: handle_string_specifier (in /home/diego/Documents/Git/mylibs/myunittest/get_next_line.out)
==463071==    by 0x10A10C: handle_format_specifier (in /home/diego/Documents/Git/mylibs/myunittest/get_next_line.out)
==463071==    by 0x10A050: process_format (in /home/diego/Documents/Git/mylibs/myunittest/get_next_line.out)
==463071==    by 0x109FA2: ft_snprintf (in /home/diego/Documents/Git/mylibs/myunittest/get_next_line.out)
==463071==    by 0x109544: tests (src/myunit.c:82)
==463071==    by 0x10996E: main (src/myunit.c:173)
==463071==  If you believe this happened as a result of a stack
==463071==  overflow in your program's main thread (unlikely but
==463071==  possible), you can try to increase the size of the
==463071==  main thread stack using the --main-stacksize= flag.
==463071==  The main thread stack size used in this run was 8388608.
==463071== 
==463071== HEAP SUMMARY:
==463071==     in use at exit: 0 bytes in 0 blocks
==463071==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
==463071== 
==463071== All heap blocks were freed -- no leaks are possible
==463071== 
==463071== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
==463071== 
==463071== 1 errors in context 1 of 1:
==463071== Invalid read of size 1
==463071==    at 0x10A3E8: ft_strlen (in /home/diego/Documents/Git/mylibs/myunittest/get_next_line.out)
==463071==    by 0x10A330: handle_string_specifier (in /home/diego/Documents/Git/mylibs/myunittest/get_next_line.out)
==463071==    by 0x10A10C: handle_format_specifier (in /home/diego/Documents/Git/mylibs/myunittest/get_next_line.out)
==463071==    by 0x10A050: process_format (in /home/diego/Documents/Git/mylibs/myunittest/get_next_line.out)
==463071==    by 0x109FA2: ft_snprintf (in /home/diego/Documents/Git/mylibs/myunittest/get_next_line.out)
==463071==    by 0x109544: tests (src/myunit.c:82)
==463071==    by 0x10996E: main (src/myunit.c:173)
==463071==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==463071== 
==463071== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
